plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.146'
    id 'idea'

    id "com.modrinth.minotaur" version "2.+"
    id 'de.maxhenkel.cursegradle' version '1.5.2'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
    srcDir('src/generated/resources')

    exclude("src/generated/**/.cache")
}

repositories {
    maven { url = "https://maven.michiyo.me/releases/" }

    maven {
        name = "kotori316"
        url = uri("https://maven.kotori316.com")
    }

    maven {
        name = "RyanHCode Maven"
        url = "https://maven.ryanhcode.dev/releases"
    }

    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }

    maven {
        name = 'BlameJared Maven (CrT / Bookshelf)'
        url = 'https://maven.blamejared.com'
    }

    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate

    maven {
        name = "Sleeping Town"
        url = "https://repo.sleeping.town/"
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "li.cil.oc:opencomputers:$opencomputers_version"
    api "dev.ryanhcode.sable:sable-neoforge-$minecraft_version:$sable_version"

    runtimeOnly "com.kotori316:scalablecatsforce-neoforge:$scalablecatsforce_version:with-library"

    runtimeOnly "dev.emi:emi-neoforge:1.1.24+1.21.1"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version          : minecraft_version,
            minecraft_version_range    : minecraft_version_range,
            neo_version                : neo_version,
            loader_version_range       : loader_version_range,
            mod_id                     : mod_id,
            mod_name                   : mod_name,
            mod_license                : mod_license,
            mod_version                : mod_version,
            opencomputers_version      : opencomputers_version,
            opencomputers_version_range: opencomputers_version_range,
            sable_version              : sable_version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' 
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "oc-sable"
    versionNumber = mod_version
    versionName = mod_name + " " + mod_version
    versionType = "release"
    gameVersions = [minecraft_version]
    loaders = ["neoforge"]
    uploadFile = jar.archiveFile.get().asFile
    changelog = file("CHANGELOG.md").text.replace("<VERSION>", mod_version)
    syncBodyFrom = file("README.md").text

    dependencies {
        required.project "sable"
    }
}

curseforge {
    if (System.getenv("CURSEFORGE_TOKEN") != null) {
        apiKey = System.getenv("CURSEFORGE_TOKEN")
        project {
            id = "1689369"
            releaseType = 'release'
            changelogType = 'markdown'
            changelog = rootProject.file("CHANGELOG.md").text.replace("<VERSION>", mod_version)
            addGameVersion minecraft_version
            addGameVersion "NeoForge"
            addGameVersion "Server"
            addGameVersion "Client"

            mainArtifact(jar.archiveFile.get().asFile) {
                relations {
                    requiredDependency 'opencomputers-rebooted'
                    requiredDependency 'sable'
                }
                displayName = mod_name + ' ' + project.mod_version
            }
        }
        options {
            forgeGradleIntegration = false
            javaVersionAutoDetect = false
        }
    }
}
